### ISSUE TITLE
Unable to upload directory of files

### ISSUE THREAD

**Issue by kmika11** [gdcc/python-dvuploader#10]
When adding files using `*dv.add_directory("./project/data")` as described in the instructions, I consistently receive the error: `AttributeError: module 'dvuploader' has no attribute 'add_directory'`

Full code: 
```
import dvuploader as dv

#add files
files = [
    #dv.File(filepath="./small.txt"),
    #dv.File(filepath="./small.txt"),
    #dv.File(directoryLabel="some/dir", filepath="./medium.txt"),
    #dv.File(directoryLabel="some/dir", filepath="./big.txt"),
    *dv.add_directory("./project/data"), # Add an entire directory
]

#set variables
DV_URL = "https://dataverse.harvard.edu/"
API_TOKEN = "XXXX-XXX-XXXXX-XXXXXX"
PID = "doi:10.7910/DVN/xxxxxx"

#upload files
dvuploader = dv.DVUploader(files=files)
dvuploader.upload(
    api_token=API_TOKEN,
    dataverse_url=DV_URL,
    persistent_id=PID,
    n_parallel_uploads= 2 # Whatever your instance can handle
)
```

**Comment by JR-1991** [comment]
@kmika11 Thanks for submitting! Which version are you using? The older version did not feature the `add_directory` function.

**Comment by kmika11** [comment]
Thanks for taking a look! I'm on `dvuploader                    0.2.1`. I think that's the current version?

**Comment by JR-1991** [comment]
Yes, this is the current version of the dvuploader. I tried to reproduce your error on [Colab](https://colab.research.google.com/drive/1yI6ifVTXiLygXldUWiGMM6YTixv6Wt-m?usp=sharing), but I didn't encounter the same error. 

Could you reinstall the library and check if the error persists?
